// Generated by jextract

package org.bitcoinkernel.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*btck_NotifyWarningSet)(void *, btck_Warning, const char *, size_t)
 * }
 */
public final class btck_NotifyWarningSet {

    private btck_NotifyWarningSet() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment user_data, byte warning, MemorySegment message, long message_len);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        bitcoinkernel_h.C_POINTER,
        bitcoinkernel_h.C_CHAR,
        bitcoinkernel_h.C_POINTER,
        bitcoinkernel_h.C_LONG
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = bitcoinkernel_h.upcallHandle(btck_NotifyWarningSet.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(btck_NotifyWarningSet.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment user_data, byte warning, MemorySegment message, long message_len) {
        try {
             DOWN$MH.invokeExact(funcPtr, user_data, warning, message, message_len);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

