// Generated by jextract

package org.bitcoinkernel.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int log_timestamps;
 *     int log_time_micros;
 *     int log_threadnames;
 *     int log_sourcelocations;
 *     int always_print_category_levels;
 * }
 * }
 */
public class btck_LoggingOptions {

    btck_LoggingOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        bitcoinkernel_h.C_INT.withName("log_timestamps"),
        bitcoinkernel_h.C_INT.withName("log_time_micros"),
        bitcoinkernel_h.C_INT.withName("log_threadnames"),
        bitcoinkernel_h.C_INT.withName("log_sourcelocations"),
        bitcoinkernel_h.C_INT.withName("always_print_category_levels")
    ).withName("$anon$421:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt log_timestamps$LAYOUT = (OfInt)$LAYOUT.select(groupElement("log_timestamps"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int log_timestamps
     * }
     */
    public static final OfInt log_timestamps$layout() {
        return log_timestamps$LAYOUT;
    }

    private static final long log_timestamps$OFFSET = $LAYOUT.byteOffset(groupElement("log_timestamps"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int log_timestamps
     * }
     */
    public static final long log_timestamps$offset() {
        return log_timestamps$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int log_timestamps
     * }
     */
    public static int log_timestamps(MemorySegment struct) {
        return struct.get(log_timestamps$LAYOUT, log_timestamps$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int log_timestamps
     * }
     */
    public static void log_timestamps(MemorySegment struct, int fieldValue) {
        struct.set(log_timestamps$LAYOUT, log_timestamps$OFFSET, fieldValue);
    }

    private static final OfInt log_time_micros$LAYOUT = (OfInt)$LAYOUT.select(groupElement("log_time_micros"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int log_time_micros
     * }
     */
    public static final OfInt log_time_micros$layout() {
        return log_time_micros$LAYOUT;
    }

    private static final long log_time_micros$OFFSET = $LAYOUT.byteOffset(groupElement("log_time_micros"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int log_time_micros
     * }
     */
    public static final long log_time_micros$offset() {
        return log_time_micros$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int log_time_micros
     * }
     */
    public static int log_time_micros(MemorySegment struct) {
        return struct.get(log_time_micros$LAYOUT, log_time_micros$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int log_time_micros
     * }
     */
    public static void log_time_micros(MemorySegment struct, int fieldValue) {
        struct.set(log_time_micros$LAYOUT, log_time_micros$OFFSET, fieldValue);
    }

    private static final OfInt log_threadnames$LAYOUT = (OfInt)$LAYOUT.select(groupElement("log_threadnames"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int log_threadnames
     * }
     */
    public static final OfInt log_threadnames$layout() {
        return log_threadnames$LAYOUT;
    }

    private static final long log_threadnames$OFFSET = $LAYOUT.byteOffset(groupElement("log_threadnames"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int log_threadnames
     * }
     */
    public static final long log_threadnames$offset() {
        return log_threadnames$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int log_threadnames
     * }
     */
    public static int log_threadnames(MemorySegment struct) {
        return struct.get(log_threadnames$LAYOUT, log_threadnames$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int log_threadnames
     * }
     */
    public static void log_threadnames(MemorySegment struct, int fieldValue) {
        struct.set(log_threadnames$LAYOUT, log_threadnames$OFFSET, fieldValue);
    }

    private static final OfInt log_sourcelocations$LAYOUT = (OfInt)$LAYOUT.select(groupElement("log_sourcelocations"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int log_sourcelocations
     * }
     */
    public static final OfInt log_sourcelocations$layout() {
        return log_sourcelocations$LAYOUT;
    }

    private static final long log_sourcelocations$OFFSET = $LAYOUT.byteOffset(groupElement("log_sourcelocations"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int log_sourcelocations
     * }
     */
    public static final long log_sourcelocations$offset() {
        return log_sourcelocations$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int log_sourcelocations
     * }
     */
    public static int log_sourcelocations(MemorySegment struct) {
        return struct.get(log_sourcelocations$LAYOUT, log_sourcelocations$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int log_sourcelocations
     * }
     */
    public static void log_sourcelocations(MemorySegment struct, int fieldValue) {
        struct.set(log_sourcelocations$LAYOUT, log_sourcelocations$OFFSET, fieldValue);
    }

    private static final OfInt always_print_category_levels$LAYOUT = (OfInt)$LAYOUT.select(groupElement("always_print_category_levels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int always_print_category_levels
     * }
     */
    public static final OfInt always_print_category_levels$layout() {
        return always_print_category_levels$LAYOUT;
    }

    private static final long always_print_category_levels$OFFSET = $LAYOUT.byteOffset(groupElement("always_print_category_levels"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int always_print_category_levels
     * }
     */
    public static final long always_print_category_levels$offset() {
        return always_print_category_levels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int always_print_category_levels
     * }
     */
    public static int always_print_category_levels(MemorySegment struct) {
        return struct.get(always_print_category_levels$LAYOUT, always_print_category_levels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int always_print_category_levels
     * }
     */
    public static void always_print_category_levels(MemorySegment struct, int fieldValue) {
        struct.set(always_print_category_levels$LAYOUT, always_print_category_levels$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

