// Generated by jextract

package org.bitcoinkernel.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     void *user_data;
 *     btck_DestroyCallback user_data_destroy;
 *     btck_NotifyBlockTip block_tip;
 *     btck_NotifyHeaderTip header_tip;
 *     btck_NotifyProgress progress;
 *     btck_NotifyWarningSet warning_set;
 *     btck_NotifyWarningUnset warning_unset;
 *     btck_NotifyFlushError flush_error;
 *     btck_NotifyFatalError fatal_error;
 * }
 * }
 */
public class btck_NotificationInterfaceCallbacks {

    btck_NotificationInterfaceCallbacks() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        bitcoinkernel_h.C_POINTER.withName("user_data"),
        bitcoinkernel_h.C_POINTER.withName("user_data_destroy"),
        bitcoinkernel_h.C_POINTER.withName("block_tip"),
        bitcoinkernel_h.C_POINTER.withName("header_tip"),
        bitcoinkernel_h.C_POINTER.withName("progress"),
        bitcoinkernel_h.C_POINTER.withName("warning_set"),
        bitcoinkernel_h.C_POINTER.withName("warning_unset"),
        bitcoinkernel_h.C_POINTER.withName("flush_error"),
        bitcoinkernel_h.C_POINTER.withName("fatal_error")
    ).withName("$anon$378:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout user_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static final AddressLayout user_data$layout() {
        return user_data$LAYOUT;
    }

    private static final long user_data$OFFSET = $LAYOUT.byteOffset(groupElement("user_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static final long user_data$offset() {
        return user_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static MemorySegment user_data(MemorySegment struct) {
        return struct.get(user_data$LAYOUT, user_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static void user_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_data$LAYOUT, user_data$OFFSET, fieldValue);
    }

    private static final AddressLayout user_data_destroy$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_data_destroy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_DestroyCallback user_data_destroy
     * }
     */
    public static final AddressLayout user_data_destroy$layout() {
        return user_data_destroy$LAYOUT;
    }

    private static final long user_data_destroy$OFFSET = $LAYOUT.byteOffset(groupElement("user_data_destroy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_DestroyCallback user_data_destroy
     * }
     */
    public static final long user_data_destroy$offset() {
        return user_data_destroy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_DestroyCallback user_data_destroy
     * }
     */
    public static MemorySegment user_data_destroy(MemorySegment struct) {
        return struct.get(user_data_destroy$LAYOUT, user_data_destroy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_DestroyCallback user_data_destroy
     * }
     */
    public static void user_data_destroy(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_data_destroy$LAYOUT, user_data_destroy$OFFSET, fieldValue);
    }

    private static final AddressLayout block_tip$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("block_tip"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_NotifyBlockTip block_tip
     * }
     */
    public static final AddressLayout block_tip$layout() {
        return block_tip$LAYOUT;
    }

    private static final long block_tip$OFFSET = $LAYOUT.byteOffset(groupElement("block_tip"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_NotifyBlockTip block_tip
     * }
     */
    public static final long block_tip$offset() {
        return block_tip$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_NotifyBlockTip block_tip
     * }
     */
    public static MemorySegment block_tip(MemorySegment struct) {
        return struct.get(block_tip$LAYOUT, block_tip$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_NotifyBlockTip block_tip
     * }
     */
    public static void block_tip(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(block_tip$LAYOUT, block_tip$OFFSET, fieldValue);
    }

    private static final AddressLayout header_tip$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("header_tip"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_NotifyHeaderTip header_tip
     * }
     */
    public static final AddressLayout header_tip$layout() {
        return header_tip$LAYOUT;
    }

    private static final long header_tip$OFFSET = $LAYOUT.byteOffset(groupElement("header_tip"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_NotifyHeaderTip header_tip
     * }
     */
    public static final long header_tip$offset() {
        return header_tip$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_NotifyHeaderTip header_tip
     * }
     */
    public static MemorySegment header_tip(MemorySegment struct) {
        return struct.get(header_tip$LAYOUT, header_tip$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_NotifyHeaderTip header_tip
     * }
     */
    public static void header_tip(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(header_tip$LAYOUT, header_tip$OFFSET, fieldValue);
    }

    private static final AddressLayout progress$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("progress"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_NotifyProgress progress
     * }
     */
    public static final AddressLayout progress$layout() {
        return progress$LAYOUT;
    }

    private static final long progress$OFFSET = $LAYOUT.byteOffset(groupElement("progress"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_NotifyProgress progress
     * }
     */
    public static final long progress$offset() {
        return progress$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_NotifyProgress progress
     * }
     */
    public static MemorySegment progress(MemorySegment struct) {
        return struct.get(progress$LAYOUT, progress$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_NotifyProgress progress
     * }
     */
    public static void progress(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(progress$LAYOUT, progress$OFFSET, fieldValue);
    }

    private static final AddressLayout warning_set$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("warning_set"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_NotifyWarningSet warning_set
     * }
     */
    public static final AddressLayout warning_set$layout() {
        return warning_set$LAYOUT;
    }

    private static final long warning_set$OFFSET = $LAYOUT.byteOffset(groupElement("warning_set"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_NotifyWarningSet warning_set
     * }
     */
    public static final long warning_set$offset() {
        return warning_set$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_NotifyWarningSet warning_set
     * }
     */
    public static MemorySegment warning_set(MemorySegment struct) {
        return struct.get(warning_set$LAYOUT, warning_set$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_NotifyWarningSet warning_set
     * }
     */
    public static void warning_set(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(warning_set$LAYOUT, warning_set$OFFSET, fieldValue);
    }

    private static final AddressLayout warning_unset$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("warning_unset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_NotifyWarningUnset warning_unset
     * }
     */
    public static final AddressLayout warning_unset$layout() {
        return warning_unset$LAYOUT;
    }

    private static final long warning_unset$OFFSET = $LAYOUT.byteOffset(groupElement("warning_unset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_NotifyWarningUnset warning_unset
     * }
     */
    public static final long warning_unset$offset() {
        return warning_unset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_NotifyWarningUnset warning_unset
     * }
     */
    public static MemorySegment warning_unset(MemorySegment struct) {
        return struct.get(warning_unset$LAYOUT, warning_unset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_NotifyWarningUnset warning_unset
     * }
     */
    public static void warning_unset(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(warning_unset$LAYOUT, warning_unset$OFFSET, fieldValue);
    }

    private static final AddressLayout flush_error$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("flush_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_NotifyFlushError flush_error
     * }
     */
    public static final AddressLayout flush_error$layout() {
        return flush_error$LAYOUT;
    }

    private static final long flush_error$OFFSET = $LAYOUT.byteOffset(groupElement("flush_error"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_NotifyFlushError flush_error
     * }
     */
    public static final long flush_error$offset() {
        return flush_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_NotifyFlushError flush_error
     * }
     */
    public static MemorySegment flush_error(MemorySegment struct) {
        return struct.get(flush_error$LAYOUT, flush_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_NotifyFlushError flush_error
     * }
     */
    public static void flush_error(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(flush_error$LAYOUT, flush_error$OFFSET, fieldValue);
    }

    private static final AddressLayout fatal_error$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("fatal_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_NotifyFatalError fatal_error
     * }
     */
    public static final AddressLayout fatal_error$layout() {
        return fatal_error$LAYOUT;
    }

    private static final long fatal_error$OFFSET = $LAYOUT.byteOffset(groupElement("fatal_error"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_NotifyFatalError fatal_error
     * }
     */
    public static final long fatal_error$offset() {
        return fatal_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_NotifyFatalError fatal_error
     * }
     */
    public static MemorySegment fatal_error(MemorySegment struct) {
        return struct.get(fatal_error$LAYOUT, fatal_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_NotifyFatalError fatal_error
     * }
     */
    public static void fatal_error(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(fatal_error$LAYOUT, fatal_error$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

