// Generated by jextract

package org.bitcoinkernel.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     void *user_data;
 *     btck_DestroyCallback user_data_destroy;
 *     btck_ValidationInterfaceBlockChecked block_checked;
 *     btck_ValidationInterfacePoWValidBlock pow_valid_block;
 *     btck_ValidationInterfaceBlockConnected block_connected;
 *     btck_ValidationInterfaceBlockDisconnected block_disconnected;
 * }
 * }
 */
public class btck_ValidationInterfaceCallbacks {

    btck_ValidationInterfaceCallbacks() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        bitcoinkernel_h.C_POINTER.withName("user_data"),
        bitcoinkernel_h.C_POINTER.withName("user_data_destroy"),
        bitcoinkernel_h.C_POINTER.withName("block_checked"),
        bitcoinkernel_h.C_POINTER.withName("pow_valid_block"),
        bitcoinkernel_h.C_POINTER.withName("block_connected"),
        bitcoinkernel_h.C_POINTER.withName("block_disconnected")
    ).withName("$anon$353:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout user_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static final AddressLayout user_data$layout() {
        return user_data$LAYOUT;
    }

    private static final long user_data$OFFSET = $LAYOUT.byteOffset(groupElement("user_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static final long user_data$offset() {
        return user_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static MemorySegment user_data(MemorySegment struct) {
        return struct.get(user_data$LAYOUT, user_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static void user_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_data$LAYOUT, user_data$OFFSET, fieldValue);
    }

    private static final AddressLayout user_data_destroy$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_data_destroy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_DestroyCallback user_data_destroy
     * }
     */
    public static final AddressLayout user_data_destroy$layout() {
        return user_data_destroy$LAYOUT;
    }

    private static final long user_data_destroy$OFFSET = $LAYOUT.byteOffset(groupElement("user_data_destroy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_DestroyCallback user_data_destroy
     * }
     */
    public static final long user_data_destroy$offset() {
        return user_data_destroy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_DestroyCallback user_data_destroy
     * }
     */
    public static MemorySegment user_data_destroy(MemorySegment struct) {
        return struct.get(user_data_destroy$LAYOUT, user_data_destroy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_DestroyCallback user_data_destroy
     * }
     */
    public static void user_data_destroy(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_data_destroy$LAYOUT, user_data_destroy$OFFSET, fieldValue);
    }

    private static final AddressLayout block_checked$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("block_checked"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_ValidationInterfaceBlockChecked block_checked
     * }
     */
    public static final AddressLayout block_checked$layout() {
        return block_checked$LAYOUT;
    }

    private static final long block_checked$OFFSET = $LAYOUT.byteOffset(groupElement("block_checked"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_ValidationInterfaceBlockChecked block_checked
     * }
     */
    public static final long block_checked$offset() {
        return block_checked$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_ValidationInterfaceBlockChecked block_checked
     * }
     */
    public static MemorySegment block_checked(MemorySegment struct) {
        return struct.get(block_checked$LAYOUT, block_checked$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_ValidationInterfaceBlockChecked block_checked
     * }
     */
    public static void block_checked(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(block_checked$LAYOUT, block_checked$OFFSET, fieldValue);
    }

    private static final AddressLayout pow_valid_block$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pow_valid_block"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_ValidationInterfacePoWValidBlock pow_valid_block
     * }
     */
    public static final AddressLayout pow_valid_block$layout() {
        return pow_valid_block$LAYOUT;
    }

    private static final long pow_valid_block$OFFSET = $LAYOUT.byteOffset(groupElement("pow_valid_block"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_ValidationInterfacePoWValidBlock pow_valid_block
     * }
     */
    public static final long pow_valid_block$offset() {
        return pow_valid_block$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_ValidationInterfacePoWValidBlock pow_valid_block
     * }
     */
    public static MemorySegment pow_valid_block(MemorySegment struct) {
        return struct.get(pow_valid_block$LAYOUT, pow_valid_block$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_ValidationInterfacePoWValidBlock pow_valid_block
     * }
     */
    public static void pow_valid_block(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pow_valid_block$LAYOUT, pow_valid_block$OFFSET, fieldValue);
    }

    private static final AddressLayout block_connected$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("block_connected"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_ValidationInterfaceBlockConnected block_connected
     * }
     */
    public static final AddressLayout block_connected$layout() {
        return block_connected$LAYOUT;
    }

    private static final long block_connected$OFFSET = $LAYOUT.byteOffset(groupElement("block_connected"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_ValidationInterfaceBlockConnected block_connected
     * }
     */
    public static final long block_connected$offset() {
        return block_connected$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_ValidationInterfaceBlockConnected block_connected
     * }
     */
    public static MemorySegment block_connected(MemorySegment struct) {
        return struct.get(block_connected$LAYOUT, block_connected$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_ValidationInterfaceBlockConnected block_connected
     * }
     */
    public static void block_connected(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(block_connected$LAYOUT, block_connected$OFFSET, fieldValue);
    }

    private static final AddressLayout block_disconnected$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("block_disconnected"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * btck_ValidationInterfaceBlockDisconnected block_disconnected
     * }
     */
    public static final AddressLayout block_disconnected$layout() {
        return block_disconnected$LAYOUT;
    }

    private static final long block_disconnected$OFFSET = $LAYOUT.byteOffset(groupElement("block_disconnected"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * btck_ValidationInterfaceBlockDisconnected block_disconnected
     * }
     */
    public static final long block_disconnected$offset() {
        return block_disconnected$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * btck_ValidationInterfaceBlockDisconnected block_disconnected
     * }
     */
    public static MemorySegment block_disconnected(MemorySegment struct) {
        return struct.get(block_disconnected$LAYOUT, block_disconnected$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * btck_ValidationInterfaceBlockDisconnected block_disconnected
     * }
     */
    public static void block_disconnected(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(block_disconnected$LAYOUT, block_disconnected$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

